import Head from 'next/head'
import { Inter } from 'next/font/google'
import SWRQoutes from '../components/qoutesSWR'
import useSWR from 'swr'
import { useGetPosts } from '../components/Qoutes'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: posts, error } = useGetPosts();
    
  if (error) return <h1>Something went wrong!</h1>;
  if (!posts) return <h1>Loading...</h1>;

  // const { data: qoutes, error } = useGetPosts();
    
  // if (error) return <h1>Something went wrong!</h1>;
  // if (!qoutes) return <h1>Loading...</h1>;

  return (
    <>
      <Head>
        <title>Next PWA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className="max-w-xl mx-auto">
        <h1 className="font-bold m-5">QOUTES</h1>
        {qoutes.map((qoute) => (
          <SWRQoutes qoute={qoute} key={qoute.id} />
        ))}
      </main> */}
      <main className="max-w-xl mx-auto">
        <h1 className="font-bold m-5">My Posts</h1>
        {posts.map((post) => (
          <SWRQoutes post={post} key={post.id} />
        ))}
      </main>
    </>
  )
}
